s  = set()
n = input("enter the number 1:")
s.add(int(n))
n = input("enter the number 2:")
s.add(int(n))
n = input("enter the number 3:")
s.add(int(n))
n = input("enter the number 4:")
s.add(int(n))
n = input("enter the number 5:")
s.add(int(n))
n = input("enter the number 6:")
s.add(int(n))
n = input("enter the number 7:")
s.add(int(n))
n = input("enter the number 8:")
s.add(int(n))
print(s)